### PR TITLE
feat: Random walking around in spoofed location

### PR DESCRIPTION
**Pull request by w451**
Title. Translations needed. Semi-realistic automatic walking around within a radius of the spoofed location so it looks like you are active. Apologies for my unfamiliarity with Kotlin.

### CODE REVIEW

**Comment by authorisation** [comment]
Thanks for your contribution, this will be merged around v2.1.0 or so.

Feel free to add yourself to the [contributors list](https://github.com/rhunk/SnapEnhance?tab=readme-ov-file#contributors).

**Comment by aternosbot90** [comment]
Fingerprint unlock

**Comment by ReSo7200** [comment]
brilliant 👏🏼 😍

**Comment by authorisation** [comment]
@bocajthomas Stop touching pull requests which are not yours.

**Comment by bocajthomas** [comment]
> @bocajthomas Stop touching pull requests which are not yours.

My bad 😔

**Pull request merged**
