### PR TITLE
feat: Chat Purge

### PR DESCRIPTION
**Pull request by TheVisual**
- Delete all messages sent by you even if saved.

Yes, I know this feature was denied but I looked at your source and you calling the same function for auto save messages. Which means there shouldn't be a problem?

Anyway open for feed back I tested it works.

image

### CODE REVIEW

**Comment by rhunk** [comment]
@TheVisual Wow that's great however it doesn't delete the entire conversation (if you're too lazy to scroll)
I've already implemented this kind of thing, check https://github.com/rhunk/SnapEnhance/blob/main/app/src/main/kotlin/me/rhunk/snapenhance/action/impl/ExportChatMessages.kt#L194C1-L208C10

**Comment by TheVisual** [comment]
@rhunk no_messages_found i tried everything maybe cuz 12.48 broke stuff. i'll look soon.

**Comment by Jeffdow85** [comment]
> * Delete all messages sent by you even if saved.
> 
> Yes, I know this feature was denied but I looked at your source and you calling the same function for auto save messages. Which means there shouldn't be a problem?
> 
> Anyway open for feed back I tested it works.
> 
> image

Thankyou good feature. One I'd love and I'm no coder by any means so if I'm not meant to ask here I apologize wasn't sure if there was a active discussion group on any other platforms. Be nice to be able to export/import  saved settings in snap enhance module! Just so you don't lose evetthing if you're swapping between new debug builds and official or for any other reason it gets uinstalled and reinstalled be fantastic to have that and get your whole feed of downloaded content back as it doesn't come back even when installed to the old directory! Can't remember what the other thing was now but won't ask too much incase this isn't the place even lol. Thanks for all the devs working on this. Brings back fond memories of other xposed modules that made snapchat amazing way beyond its time. And being able to do it unrooted is super cool too less chance of account bans perhaps since it's not a 3rd party apk even if signature changes ok probably still a breach of their tos and but whatever I like the root free option and it works fine, a little buggy at times just crashes etc but nothing a force close doesn't fix! ❤️

**Comment by TheVisual** [comment]
> > * Delete all messages sent by you even if saved.
> > 
> > Yes, I know this feature was denied but I looked at your source and you calling the same function for auto save messages. Which means there shouldn't be a problem?
> > Anyway open for feed back I tested it works.
> > image
> 
> Thankyou good feature. One I'd love and I'm no coder by any means so if I'm not meant to ask here I apologize wasn't sure if there was a active discussion group on any other platforms. Be nice to be able to export/import saved settings in snap enhance module! Just so you don't lose evetthing if you're swapping between new debug builds and official or for any other reason it gets uinstalled and reinstalled be fantastic to have that and get your whole feed of downloaded content back as it doesn't come back even when installed to the old directory! Can't remember what the other thing was now but won't ask too much incase this isn't the place even lol. Thanks for all the devs working on this. Brings back fond memories of other xposed modules that made snapchat amazing way beyond its time. And being able to do it unrooted is super cool too less chance of account bans perhaps since it's not a 3rd party apk even if signature changes ok probably still a breach of their tos and but whatever I like the root free option and it works fine, a little buggy at times just crashes etc but nothing a force close doesn't fix! ❤️

Open a issue with the suggestion atm I'm very busy. First i'd like to finish this.

**Comment by RSR1337** [comment]
Stop spamming me scammer

**Comment by TheVisual** [comment]
@rhunk @authorisation it's ready for review 👍

**Comment by TheVisual** [comment]
https://github.com/rhunk/SnapEnhance/commit/c533983fb3ee67d4a744ca7e85c80287ce87bf28

Planned for V2 will contribute stuff there

**Pull request closed without merging**
