### PR TITLE
Add Workflows and Update Dependencies

### PR DESCRIPTION
**Pull request by CanerKaraca23**
Added Dependabot and Gradle Wrapper Updater workflows to automatically detect dependency and Gradle wrapper updates and create pull requests to update them.

Updated some dependencies and Gradle wrapper.

### CODE REVIEW

**Review by CanerKaraca23 — COMMENTED** [review]
Build passes.

**Review by authorisation — COMMENTED** [review]
Looks good, feel free to add yourself to the README.
Merging soon if you have nothing else to add.
Thanks for your contribution :)

**Review by authorisation — APPROVED** [review]

**Comment by CanerKaraca23** [comment]
> Looks good, feel free to add yourself to the README. Merging soon if you have nothing else to add. Thanks for your contribution :)

Thanks! I added. I don't have anything to add, you can merge.

**Comment by CanerKaraca23** [comment]
I also translated 100% of Turkish localization on Crowdin, can you add it too?

**Pull request merged**
