### PR TITLE
Edit README to reflect account bans

### PR DESCRIPTION
**Pull request by FirePlank**
I removed the statement about no reported cases of bans, as it is no longer accurate. The updated text now advises users to use the mod at their own risk, acknowledging the possibility of account suspension or ban.

### CODE REVIEW

**Comment by authorisation** [comment]
The statement is still accurate, no one has been banned so far. Although might merge this later when it does happen.

**Comment by FirePlank** [comment]
Even if no one has been official 'banned' yet and its only an account suspension/time out. The text should still be changed since it gives a false sense of security to the user thinking they won't be repremanded for using this mod. Saying the risk is 'very low' when right now at least, the mod is being detected everytime doesn't really seem like the right thing to say.

**Comment by authorisation** [comment]
Hmm, I agree.

**Comment by DisabledGoop** [comment]
I can confirm 100% that I have been **banned** on multiple accounts over the last month, never even received a warning nor a message on screen.  Native Hooks option *not* enabled, only 'safe' options.

Happens at random times, not during any specific event.  Sometimes the account is alive for 24 hours, other times a few days.

Last night I added a friend.  The moment i clicked "Add", the account signed out.  No message, just a sign-out.  Permaban, non-unlockable.  Even got the email saying so.  That tells me it's punitive.

**Comment by authorisation** [comment]
> I can confirm 100% that I have been **banned** on multiple accounts over the last month, never even received a warning nor a message on screen. Native Hooks option _not_ enabled, only 'safe' options.
> 
> Happens at random times, not during any specific event. Sometimes the account is alive for 24 hours, other times a few days.
> 
> Last night I added a friend. The moment i clicked "Add", the account signed out. No message, just a sign-out. Permaban, non-unlockable. Even got the email saying so. That tells me it's punitive.

Yeah not related to SE at all

**Pull request merged**
