### PR TITLE
chore(readme): v2.0.2

### PR DESCRIPTION
**Pull request by bocajthomas**
Merge after stable release

### CODE REVIEW

**Comment by bocajthomas** [comment]
Merge after stable release

**Review by aternosbot90 — APPROVED** [review]

**Comment by aternosbot90** [comment]
> Merge after stable release 

Why the relationship notifier deleted?

**Comment by bocajthomas** [comment]
> Why the relationship notifier deleted?

Because it's Called "Friend Mutation Notifier" 
And not Relationship notifier now

**Comment by aternosbot90** [comment]
> > Why the relationship notifier deleted?
> 
> @aternosbot90 Because it's Called "Friend Mutation Notifier" 
> And not Relationship notifier now 
> 

Okie 🙃

**Review by Atrr208 — COMMENTED** [review]
README.md

**Pull request merged**
