### PR TITLE
[WIP] Update fstat_hook.h

### PR DESCRIPTION
**Pull request by VendorAttestation**
- Fixed login sus activity on my pixel 5 with login issues

### CODE REVIEW

**Comment by TheVisual** [comment]
Somehow i'd like to

```
    "init.svc.adbd": "stopped",
```

**Comment by Yoganshbhatt** [comment]
Hello! I was curious if this build should work as a fix for recent detection warning for people like me on aosp based custom roms.

**Comment by TheVisual** [comment]
> Hello! I was curious if this build should work as a fix for recent detection warning for people like me on aosp based custom roms.

No but this fixes sus login on some devices 👍 

rhunk shall fix the detection soon 💯 he's just taking a small break


also note this a wip `init.svc.adbd:stopped still needs to be done`

**Comment by bocajthomas** [comment]
> * Fixed login sus activity on my pixel 5 with login issues

This is gonna sit here of a while 😶

**Pull request closed without merging**
