### PR TITLE
Added translation 

### PR DESCRIPTION
**Pull request by bocajthomas**
Added:
English ( UK )

### CODE REVIEW

**Comment by Theonethom** [comment]
@authorisation why close ? 
Uk English Isn't On Weblate 
Better to just side it into the Lang Folder

**Comment by authorisation** [comment]
I diff checked en_US and en_UK, they're the exact same with the only difference being a couple of new strings which are not present in the source file.

**Comment by bocajthomas** [comment]
> I diff checked en_US and en_UK, they're the exact same with the only difference being a couple of new strings which are not present in the source file.

In the UK we speak spell  things Differently
It really annoys Me that the only Supported English language is The US!!

**Comment by bocajthomas** [comment]
> I diff checked en_US and en_UK, they're the exact same with the only difference being a couple of new strings which are not present in the source file.

Also i put on draft cuz I haven't finished with it !

**Comment by authorisation** [comment]
https://hosted.weblate.org/projects/snapenhance/app/en_UK/

**Pull request closed without merging**
