### PR TITLE
chore: update translations

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [SnapEnhance/SnapEnhance](https://hosted.weblate.org/projects/snapenhance/app/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by IamNickerson** [comment]
Add language Malayalam

**Comment by IamNickerson** [comment]
The word Stealth Mode is being used twice in two different keys why is that?
image

**Comment by IamNickerson** [comment]
image
Can someone just delete this same word with a different key on it

**Comment by authorisation** [comment]
> image Can someone just delete this same word with a different key on it

It's fine. Would be better if it was removed but meh

**Pull request merged**
