### PR TITLE
Update Workflows and Dependencies

### PR DESCRIPTION
**Pull request by CanerKaraca23**
- Use JDK 21
 - Updated dependencies (Except Material3, compose-bom, coil and ffmpeg-kit due to issues)
 - Updated Gradle
 - Use ubuntu instead of MacOS on Beta CI (decreasing actions time by almost 50%)
 - Use JUnit Vintage Engine instead of JUnit 4 or JUnit 5 (JUnit Jupiter)
(The junit-vintage-engine is designed for tests written in older versions of JUnit, such as JUnit 3 and JUnit 4. This engine provides backward compatibility with older versions of JUnit. Additionally, it allows using older tests while taking advantage of the new JUnit 5 features)

### CODE REVIEW

**Comment by CanerKaraca23** [comment]
Also don't know why use this steps:

`      - name: Generate Version
        run: ./gradlew getVersion

      - name: Set Version to Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/SnapEnhance-${{ env.version }}-ARMv8-${{ steps.version-env.outputs.sha_short }}.apk
`

**Comment by CanerKaraca23** [comment]
Also don't know why use this steps:

`- name: Generate Version
        run: ./gradlew getVersion

      - name: Set Version to Environment Variables
        id: version-env
        run: |
          echo "version=$(cat app/build/version.txt)" >> $GITHUB_ENV
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Git Branch Name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@main

      - name: Rename APK File
        run: |
          mv app/build/outputs/apk/armv8/debug/*.apk app/build/outputs/apk/armv8/debug/SnapEnhance-${{ env.version }}-ARMv8-${{ steps.version-env.outputs.sha_short }}.apk`

**Comment by authorisation** [comment]
For fancy naming

**Comment by CanerKaraca23** [comment]
New versions of material3 and compose bom breaks app, so reverted back.

**Comment by rhunk** [comment]
@CanerKaraca23 I don't think there's any need to constantly update to the latest versions of the libraries, as there isn't much of necessity. Every time you update a library, I have to compile a build in release (which takes some time) and check that everything is working properly. However, if there are known security flaws, updates would be very important

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 I don't think there's any need to constantly update to the latest versions of the libraries, as there isn't much of necessity. Every time you update a library, I have to compile a build in release (which takes some time) and check that everything is working properly. However, if there are known security flaws, updates would be very important

I think updating libraries to latest versions is always good because it's not only for security, every update contains bug fixes and stability improvements and it's good. I think using latest versions is always good. I'm testing the app if there is anything broken, for example, material3 and compose bom breaks app (don't know why) and i reverted back. Thanks.

**Comment by CanerKaraca23** [comment]
@rhunk I will not push any updates anymore, can you review and test? No issue so far, i'm using with this build without any problem.

**Review by authorisation — CHANGES_REQUESTED** [review]
I do not like the workflow edits, revert them. 
Everyting else is approved.

**Comment by CanerKaraca23** [comment]
> I do not like the workflow edits, revert them. Everyting else is approved.

Ok. Which parts you want me to revert?

**Comment by authorisation** [comment]
Everything

**Pull request merged**
