### PR TITLE
FFmpeg Improvements

### PR DESCRIPTION
**Pull request by TheVisual**
Bump ffmpeg-kit -> 6.0-2.LTS
Default -hwaccel mediacodec
Change libx264 -> h264_mediacodec

https://developer.android.com/reference/android/media/MediaCodec

Tested here is a sample video https://gofile.io/d/LV1s5H (Download Raw File for Improvements)

Tested on Iphone / Android / Windows video played on all

MediaCodec is androids codec I've seen many great improvements for quality

### CODE REVIEW

**Comment by TheVisual** [comment]
Before we push i need ffmpeg-kit testers for the new encoding as this is a major LTS upgrade

**Comment by TheVisual** [comment]
> .

I'm going to focus on FFmpeg on this build if you want to test dependences stuff move towards new PR

**Comment by TheVisual** [comment]
@CanerKaraca23 It doesn't break anything tbh removed that old comment its just better practice to use LTS (Long Time Support)

**Comment by authorisation** [comment]
IIRC @CanerKaraca23 already made a pull request before and updating ffmpeg-kit broke something.

**Comment by TheVisual** [comment]
> IIRC @CanerKaraca23 already made a pull request before and updating ffmpeg-kit broke something.

I've had a few people test this new LTS build with FFMPEG stuff seems to work? Where did i break so i can test

**Comment by authorisation** [comment]
I think merging this for v2.1.0 while everything else gets tested first would fit nicely. I want to make sure v2.0.x doesn't have any major flaws first.

**Comment by authorisation** [comment]
Also maybe a stripped down ffmpeg-kit custom build would be better, the current kit makes the APKs really huge.

https://github.com/SnapEnhance/ffmpeg

**Comment by TheVisual** [comment]
> Also maybe a stripped down ffmpeg-kit custom build would be better, the current kit makes the APKs really huge.
> 
> https://github.com/SnapEnhance/ffmpeg

any reason you killed --enable-android-media-codec we kinda need that :)

**Comment by authorisation** [comment]
> > Also maybe a stripped down ffmpeg-kit custom build would be better, the current kit makes the APKs really huge.
> > https://github.com/SnapEnhance/ffmpeg
> 
> any reason you killed --enable-android-media-codec we kinda need that :)

My bad, I'm trying to get it to compile in the first place, I'll add it in a second

**Comment by TheVisual** [comment]
> > > Also maybe a stripped down ffmpeg-kit custom build would be better, the current kit makes the APKs really huge.
> > > https://github.com/SnapEnhance/ffmpeg
> > 
> > 
> > any reason you killed --enable-android-media-codec we kinda need that :)
> 
> My bad, I'm trying to get it to compile in the first place, I'll add it in a second

Also `--enable-opus` probably not needed as i don't think windows PC / other platforms can even play it by default so very rare use cases because they'll have to open in VLC also we should enable `--enable-x265` (https://en.wikipedia.org/wiki/X265) for people who want to compress video's more with no quality loss just my opinion tho

**Comment by bocajthomas** [comment]
Screenshot_20240415_033044_SnapEnhance

Didn't really use it untill you opened a PR but Have a look 
Old version I'll test new tmz

**Comment by TheVisual** [comment]
Also @authorisation 

https://github.com/arthenica/ffmpeg-kit/wiki/Building-FFmpegKit-with-Custom-Libraries

https://github.com/mstorsjo/fdk-aac

We should build with libfdk-aac (https://github.com/arthenica/ffmpeg-kit/issues/581) says we need to edit the config

libfdk-aac compiles audio faster (on android) then normal aac and is generally more stable just putting this here for future reference if we decide to add.

**Pull request merged**
